version: '3.1'

services:

  db:
    image: postgres
    restart: always
    environment:
      POSTGRES_HOST_AUTH_METHOD: trust
      POSTGRES_PASSWORD: example
      POSTGRES_USER: app
    ports:
      - '9999:9999'
    volumes:
      - ./var/lib/postgresql/data